### ISSUE TITLE
Error when running python project

### ISSUE THREAD

**Issue by GoogleCodeExporter** [pmoulon/osm-bundler#10]
```
What steps will reproduce the problem?
1. python path_to/RunBundler.py --photo=example 

What is the expected output? What do you see instead?
Error message only

What version of the product are you using? On what operating system?
r-144-179-28-172:osm-bundler moonlight$ /usr/local/bin/python RunBundler.py 
--photo=example
Working directory created: 
/var/folders/c4/w8vrtsvs5rb6l256g889fk700000gn/T/osm-bundler-PNrQBD
BundlerMatching executable path: /Users/moonlight/Google 
Drive/nus/sem7/cs4243/osm-bundler/software/bundler/bin/KeyMatchFull
Sift executable path: /Users/moonlight/Google 
Drive/nus/sem7/cs4243/osm-bundler/software/vlfeat/bin/glx/sift

Processing photo 'IMGP3417.jpg':
    Copy of the photo has been scaled down to 1200x900
    Extracting features with the SIFT method from VLFeat library...
Traceback (most recent call last):
  File "RunBundler.py", line 9, in <module>
    manager.preparePhotos()
  File "/Users/moonlight/Google Drive/nus/sem7/cs4243/osm-bundler/osmbundler/__init__.py", line 121, in preparePhotos
    self._preparePhoto(photoInfo)
  File "/Users/moonlight/Google Drive/nus/sem7/cs4243/osm-bundler/osmbundler/__init__.py", line 176, in _preparePhoto
    self.extractFeatures(photo)
  File "/Users/moonlight/Google Drive/nus/sem7/cs4243/osm-bundler/osmbundler/__init__.py", line 244, in extractFeatures
    self.featureExtractor.extract(photo, self.photoDict[photo])
  File "/Users/moonlight/Google Drive/nus/sem7/cs4243/osm-bundler/osmbundler/features/siftvlfeat.py", line 16, in extract
    subprocess.call([self.executable, "%s.jpg.pgm" % photo, "-o", "%s.key" % photo])
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 524, in call
    return Popen(*popenargs, **kwargs).wait()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 711, in __init__
    errread, errwrite)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 1308, in _execute_child
    raise child_exception
OSError: [Errno 8] Exec format error

```

Original issue reported on code.google.com by `moonligh...@gmail.com` on 13 Sep 2013 at 4:30

**Comment by zh1609** [comment]
You need to get the 32bit libs for the 64bit system. The binaries is compiled for 32bit sysTEM.
