### ISSUE TITLE
running 

### ISSUE THREAD

**Issue by GoogleCodeExporter** [pmoulon/osm-bundler#8]
```
What steps will reproduce the problem?

using the download of osm-bundler.zip on linux 64 bit system
1.

dave@dave-desktop:~/Downloads/osm-bundler$ python RunBundler.py 
--photos=example_OldTownHall/
Working directory created: /tmp/osm-bundler-xUoC86
BundlerMatching executable path: 
/home/dave/Downloads/osm-bundler/software/bundler/bin/KeyMatchFull
Sift executable path: 
/home/dave/Downloads/osm-bundler/software/vlfeat/bin/glx/sift

Processing photo 'IMGP3428.jpg':
    Copy of the photo has been scaled down to 1200x900
    Extracting features with the SIFT method from VLFeat library...
Traceback (most recent call last):
  File "RunBundler.py", line 9, in <module>
    manager.preparePhotos()
  File "/home/dave/Downloads/osm-bundler/osmbundler/__init__.py", line 121, in preparePhotos
    self._preparePhoto(photoInfo)
  File "/home/dave/Downloads/osm-bundler/osmbundler/__init__.py", line 176, in _preparePhoto
    self.extractFeatures(photo)
  File "/home/dave/Downloads/osm-bundler/osmbundler/__init__.py", line 244, in extractFeatures
    self.featureExtractor.extract(photo, self.photoDict[photo])
  File "/home/dave/Downloads/osm-bundler/osmbundler/features/siftvlfeat.py", line 16, in extract
    subprocess.call([self.executable, "%s.jpg.pgm" % photo, "-o", "%s.key" % photo])
  File "/usr/lib/python2.7/subprocess.py", line 493, in call
    return Popen(*popenargs, **kwargs).wait()
  File "/usr/lib/python2.7/subprocess.py", line 679, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1249, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory


What is the expected output? What do you see instead?

something other than an error

What version of the product are you using? On what operating system?

latest

Please provide any additional information below.

also tried the full distribution (osm-bundler-pmvs2-cmvs-full-32-64.zip) and 
got this

dave@dave-desktop:~/Downloads/osm-bundler$ python RunBundler.py 
--photos=examples/kermit/
Traceback (most recent call last):
  File "RunBundler.py", line 2, in <module>
    import osmbundler
ImportError: No module named osmbundler

```

Original issue reported on code.google.com by `david.te...@googlemail.com` on 15 May 2013 at 9:47

**Comment by waltermayor** [comment]
hi, how are you 
```
python RunBundler.py --photos=/home/walter/Environments/proyectos/SFM-Python-Walter/mediaInput/OldTownHall/
```

```
Working directory created: /home/walter/Environments/proyectos/SFM-Python-Walter/osm-bundler-master/output/osm-bundler-A2gDqW
BundlerMatching executable path: /home/walter/Environments/proyectos/SFM-Python-Walter/osm-bundler-master/software/bundler/KeyMatchFull
Sift executable path: /home/walter/Environments/proyectos/SFM-Python-Walter/osm-bundler-master/software/sift-lowe/sift


Processing photo 'IMGP3420.jpg':
	Copy of the photo has been scaled down to 1200x900
Traceback (most recent call last):
  File "RunBundler.py", line 11, in <module>
    manager.preparePhotos()
  File "/home/walter/Environments/proyectos/SFM-Python-Walter/osm-bundler-master/osmbundler/__init__.py", line 168, in preparePhotos
    self._preparePhoto(photoInfo)
  File "/home/walter/Environments/proyectos/SFM-Python-Walter/osm-bundler-master/osmbundler/__init__.py", line 281, in _preparePhoto
    self.extractFeatures(photo)
  File "/home/walter/Environments/proyectos/SFM-Python-Walter/osm-bundler-master/osmbundler/__init__.py", line 351, in extractFeatures
    self.featureExtractor.extract(photo,self.photoDict[photo])
  File "/home/walter/Environments/proyectos/SFM-Python-Walter/osm-bundler-master/osmbundler/features/siftlowe.py", line 27, in extract
    subprocess.call(self.executable, **dict(stdin=photoFile, stdout=siftTextFile))
  File "/usr/lib/python2.7/subprocess.py", line 523, in call
    return Popen(*popenargs, **kwargs).wait()
  File "/usr/lib/python2.7/subprocess.py", line 711, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1343, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
```
I did this
``
chmod a+x /complete_path/osm-bundler/software/sift-lowe/sift
``
but the error is the same 

Could anyone help me please?

**Comment by pmoulon** [comment]
Can be a path issue.
I'm sorry I don't maintain it anymore.

Now I focus more on [OpenMVG](https://github.com/openMVG/openMVG) that is more flexible and more aligned towards giving pipeline, knowledge and code to the photogrammetry community.

**Comment by waltermayor** [comment]
hi Pierre

tk for the information

Has OpenMVG the pmvs library to use from python?

best regard

walter mayor



2018-05-22 15:14 GMT-05:00 Pierre Moulon <notifications@github.com>:

**Comment by pmoulon** [comment]
There is an easy way to use OpenMVG from Python (python is used to launch some binaries):
https://openmvg.readthedocs.io/en/latest/software/SfM/SfM/#openmvg-sfm-pipelines-demo

Then you can export OpenMVG results to many MVS frameworks (and PMVS is one of them):
https://openmvg.readthedocs.io/en/latest/software/MVS/MVS/

Some project are on github to launch all of them more easily:
see here: https://github.com/open-anatomy/SfM_gui_for_openMVG

**Comment by waltermayor** [comment]
Pierre

thanks you for your quick response


2018-05-22 19:38 GMT-05:00 Pierre Moulon <notifications@github.com>:
